import 'package:truck_app/core/constants/app_images.dart';

import '../../features/home/model/connect.dart';
import '../../features/vehicle/model/vehicle.dart';

class DummyData {
  static final List<Connect> userConnections = [
    Connect(
      id: 'u1',
      postName: 'Load Request #54321',
      replyUserName: 'Faheem',
      postTitle: 'FMCG delivery from Calicut to Trivandrum',
      dateTime: DateTime.now().subtract(const Duration(hours: 1)),
      status: ConnectStatus.pending,
      isUser: true,
    ),
    Connect(
      id: 'u2',
      postName: 'Load Request #33445',
      replyUserName: 'Rahul',
      postTitle: 'Furniture shifting to Thrissur',
      dateTime: DateTime.now().subtract(const Duration(minutes: 30)),
      status: ConnectStatus.completed,
      isUser: true,
    ),
    Connect(
      id: 'u3',
      postName: 'Load Request #99887',
      replyUserName: 'Manoj Kumar',
      postTitle: 'Urgent delivery to Hyderabad within 24h',
      dateTime: DateTime.now().subtract(const Duration(hours: 3)),
      status: ConnectStatus.pending,
      isUser: true,
    ),
    Connect(
      id: 'u4',
      postName: 'Load Request #11223',
      replyUserName: 'Sana',
      postTitle: 'Groceries to be delivered to Kochi',
      dateTime: DateTime.now().subtract(const Duration(days: 2, hours: 6)),
      status: ConnectStatus.accepted,
      isUser: true,
    ),
    Connect(
      id: 'u5',
      postName: 'Load Request #77665',
      replyUserName: 'Akash',
      postTitle: 'Electronics to Bengaluru',
      dateTime: DateTime.now().subtract(const Duration(days: 4)),
      status: ConnectStatus.rejected,
      isUser: true,
    ),
  ];

  static final List<Connect> driverConnections = [
    Connect(
      id: 'd1',
      postName: 'Vehicle Availability #90876',
      replyUserName: 'Anjali',
      postTitle: 'AC container for pharma supplies',
      dateTime: DateTime.now().subtract(const Duration(days: 3)),
      status: ConnectStatus.accepted,
      isUser: false,
    ),
    Connect(
      id: 'd2',
      postName: 'Vehicle Availability #55667',
      replyUserName: 'Sneha',
      postTitle: 'Open truck available for bulk goods',
      dateTime: DateTime.now().subtract(const Duration(days: 1, hours: 5)),
      status: ConnectStatus.rejected,
      isUser: false,
    ),
    Connect(
      id: 'd3',
      postName: 'Vehicle Availability #77889',
      replyUserName: 'Ravi',
      postTitle: '10-tonne lorry from Chennai',
      dateTime: DateTime.now().subtract(const Duration(hours: 5)),
      status: ConnectStatus.pending,
      isUser: false,
    ),
    Connect(
      id: 'd4',
      postName: 'Vehicle Availability #11290',
      replyUserName: 'Latha',
      postTitle: 'Mini truck available in Palakkad',
      dateTime: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
      status: ConnectStatus.completed,
      isUser: false,
    ),
    Connect(
      id: 'd5',
      postName: 'Vehicle Availability #22334',
      replyUserName: 'Shyam',
      postTitle: 'Truck with hydraulic lift',
      dateTime: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
      status: ConnectStatus.pending,
      isUser: false,
    ),
  ];
  static List<Vehicle> driverVehicles = [
    Vehicle(
      id: 'V001',
      type: VehicleType.largeTruck,
      bodyType: VehicleBodyType.container,
      capacity: 15.0,
      vehicleNumber: 'KL07AB1234',
      rcFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      drivingLicenseFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      truckImageUrls: [AppImages.dummyTruck1, AppImages.dummyTruck2, 'https://via.placeholder.com/600x400.png?text=Truck+2+Side'],
      goodsAccepted: ['Electronics', 'Machinery', 'Textiles'],
    ),
    Vehicle(
      id: 'V002',
      type: VehicleType.miniTruck,
      bodyType: VehicleBodyType.open,
      capacity: 2.5,
      vehicleNumber: 'KA01CD5678',
      rcFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      drivingLicenseFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      truckImageUrls: ['https://via.placeholder.com/600x400.png?text=Truck+2+Side',AppImages.dummyTruck1, AppImages.dummyTruck2, 'https://via.placeholder.com/600x400.png?text=Truck+2+Side',],
      goodsAccepted: ['Food', 'Furniture'],
    ),
    Vehicle(
      id: 'V003',
      type: VehicleType.containerTruck,
      bodyType: VehicleBodyType.closed,
      capacity: 1.0,
      vehicleNumber: 'MH12EF3456',
      rcFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      drivingLicenseFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      truckImageUrls: [AppImages.dummyTruck1,'https://via.placeholder.com/600x400.png?text=Truck+2+Side', AppImages.dummyTruck2, 'https://via.placeholder.com/600x400.png?text=Truck+2+Side'], goodsAccepted: ['Medicines', 'Groceries'],
    ),
    Vehicle(
      id: 'V004',
      type: VehicleType.trailer,
      bodyType: VehicleBodyType.open,
      capacity: 3.0,
      vehicleNumber: 'TN10GH7890',
      rcFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      drivingLicenseFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      truckImageUrls: ['https://via.placeholder.com/600x400.png?text=Truck+2+Side','https://via.placeholder.com/600x400.png?text=Truck+2+Side',AppImages.dummyTruck2, AppImages.dummyTruck2, 'https://via.placeholder.com/600x400.png?text=Truck+2+Side'], goodsAccepted: ['Plastic Items', 'Hardware'],
    ),
    Vehicle(
      id: 'V005',
      type: VehicleType.largeTruck,
      bodyType: VehicleBodyType.tipper,
      capacity: 20.0,
      vehicleNumber: 'AP03IJ1122',
      rcFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      drivingLicenseFileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      truckImageUrls: [AppImages.dummyTruck1, AppImages.dummyTruck1, 'https://via.placeholder.com/600x400.png?text=Truck+2+Side'], goodsAccepted: ['Water', 'Oil'],
    ),
  ];
}
